"""Scenario 3: WorkPackage creation + enqueue-message.

Starts from a pre-existing confirmed Spec (injected via fake_gh), runs
commit-workpackage with an impact-scope file, then enqueues a
design-approval message via enqueue-message.

Exercises the body validation + frontmatter generation + adapter chain.
"""

from __future__ import annotations

import json
import textwrap
from pathlib import Path

import pytest
from click.testing import CliRunner

from rlm.cli import main


def _write(path: Path, content: str) -> Path:
    path.write_text(content, encoding="utf-8")
    return path


WP_BODY = """# Revert calendar widget to v1.2

Restore v1.2 server-rendered snapshot of the calendar widget.

## AcceptanceCriteria

- [ ] Mobile booking conversion baseline restored
- [ ] Desktop unaffected
- [ ] Old v2.0 React state cleaned up
"""

IMPACT_SCOPE_YAML = textwrap.dedent(
    """\
    impact_scope:
      files:
        - src/calendar-widget/*
      modules:
        - the Calendar widget (Design BC)
      seams:
        - calendar-widget ↔ checkout-flow (real seam — restoring v1.2 adapter)
      contracts: []
      external_systems: []
      adr_conflicts: []
      new_contracts_needed: []
      estimated_complexity: small
      notes: |
        Revert assumes v1.2 snapshot still in git history.
    """
)


def test_wp_create_then_design_approval_message(
    runner_env: dict,  # noqa: ARG001
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    runner = CliRunner()
    fake_gh = runner_env["github"]
    repo: Path = runner_env["repo"]

    # Setup: a confirmed Spec
    spec_num = fake_gh.add_issue(
        title="Recover mobile booking conversion",
        body="---\ntype: spec\nstatus: confirmed\nsignal_ref: 142\n---\n",
        labels=["type:spec", "status:confirmed"],
    )

    # Step 1: commit-workpackage (caller: hermes-design)
    monkeypatch.setenv("RLM_AGENT_ROLE", "hermes-design")
    monkeypatch.setenv("RLM_AGENT_INVOCATION", "inv_scenario3")
    monkeypatch.setenv("RLM_SKILL_NAME", "decompose-spec")

    wp_body = _write(repo / "wp_body.md", WP_BODY)
    scope_file = _write(repo / "scope.yaml", IMPACT_SCOPE_YAML)

    result = runner.invoke(
        main,
        [
            "--json",
            "commit-workpackage",
            "--parent-spec",
            str(spec_num),
            "--title",
            "Revert calendar widget to v1.2",
            "--worker-class",
            "web-stack",
            "--impact-scope-file",
            str(scope_file),
            "--body-file",
            str(wp_body),
        ],
        catch_exceptions=False,
    )
    assert result.exit_code == 0, f"commit-workpackage failed: stderr={result.stderr}"
    out = json.loads(result.output)
    wp_num = out["issue_number"]
    assert out["status"] == "draft"
    assert out["parent_spec"] == spec_num
    assert out["adr_refs"] == []
    assert out["depends_on"] == []
    assert out["slice_type"] == "AFK"

    wp_issue = fake_gh.issues[wp_num]
    assert "type:workpackage" in wp_issue.labels
    assert "status:draft" in wp_issue.labels
    # Frontmatter generated by CLI
    assert "type: workpackage" in wp_issue.body
    assert f"parent_spec: {spec_num}" in wp_issue.body
    assert "acceptance_criteria_count: 3" in wp_issue.body
    assert "estimated_complexity: small" in wp_issue.body
    # Body content preserved after frontmatter
    assert "Restore v1.2 server-rendered snapshot" in wp_issue.body

    # Step 2: enqueue design-approval message on the WP Issue
    msg_body = _write(
        repo / "msg.md",
        f"WP #{wp_num} ready for human approval. Reply: approve / hold / discuss.",
    )
    result = runner.invoke(
        main,
        [
            "--json",
            "enqueue-message",
            "--kind",
            "design-approval",
            "--parent-issue",
            str(wp_num),
            "--body-file",
            str(msg_body),
        ],
        catch_exceptions=False,
    )
    assert result.exit_code == 0, f"enqueue-message failed: stderr={result.stderr}"
    out = json.loads(result.output)
    assert out["kind"] == "design-approval"
    assert out["parent_issue"] == wp_num

    wp_issue = fake_gh.issues[wp_num]
    assert "outbound:design-approval" in wp_issue.labels
    assert any(f"WP #{wp_num} ready" in c for c in wp_issue.comments)


def test_wp_create_rejects_unconfirmed_spec(
    runner_env: dict,  # noqa: ARG001
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    """commit-workpackage refuses if parent_spec is not status:confirmed."""
    runner = CliRunner()
    fake_gh = runner_env["github"]
    repo: Path = runner_env["repo"]

    # Draft (not yet confirmed) Spec
    spec_num = fake_gh.add_issue(
        title="Draft Spec",
        body="",
        labels=["type:spec", "status:draft"],
    )

    monkeypatch.setenv("RLM_AGENT_ROLE", "hermes-design")
    monkeypatch.setenv("RLM_AGENT_INVOCATION", "inv_reject")

    wp_body = _write(repo / "wp.md", WP_BODY)
    scope_file = _write(repo / "scope.yaml", IMPACT_SCOPE_YAML)

    result = runner.invoke(
        main,
        [
            "--json",
            "commit-workpackage",
            "--parent-spec",
            str(spec_num),
            "--title",
            "X",
            "--impact-scope-file",
            str(scope_file),
            "--body-file",
            str(wp_body),
        ],
        catch_exceptions=False,
    )
    assert result.exit_code == 6
    err = json.loads(result.stderr)
    assert err["error"] == "precondition-failed"
    assert "status:confirmed" in err["message"]


def test_enqueue_supervision_alert_creates_new_issue(
    runner_env: dict,  # noqa: ARG001
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    """enqueue-message --kind=supervision-alert creates a new type:supervision-alert Issue."""
    runner = CliRunner()
    fake_gh = runner_env["github"]
    repo: Path = runner_env["repo"]

    monkeypatch.setenv("RLM_AGENT_ROLE", "supervision")
    monkeypatch.setenv("RLM_AGENT_INVOCATION", "inv_sup")

    body = _write(
        repo / "alert.md",
        "# Stale fact detected\n\nFact `2026-04-12-foo` no longer matches code shape.\n",
    )

    result = runner.invoke(
        main,
        [
            "--json",
            "enqueue-message",
            "--kind",
            "supervision-alert",
            "--severity",
            "mid",
            "--body-file",
            str(body),
        ],
        catch_exceptions=False,
    )
    assert result.exit_code == 0, f"enqueue-message failed: stderr={result.stderr}"
    out = json.loads(result.output)
    alert_num = out["issue_number"]
    assert out["kind"] == "supervision-alert"
    assert out["severity"] == "mid"

    alert = fake_gh.issues[alert_num]
    assert "type:supervision-alert" in alert.labels
    assert "status:open" in alert.labels
    assert "severity:mid" in alert.labels
    assert alert.title == "Stale fact detected"  # extracted from first H1
